#!/usr/bin/env sh

# Recargar al finalizar la configuración
yabai -m signal --add event="application_terminated" action="killall Dock"
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config                                 \
    external_bar                 all:0:0       \
    menubar_opacity              0            \
    mouse_follows_focus          on            \
    focus_follows_mouse          autofocus            \
    focus_duration               0              \
    window_topmost               0              \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             first_child   \
    window_zoom_persist          off             \
    window_shadow                off             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        0.0            \
    normal_window_opacity        0.0           \
    window_opacity               off            \
    insert_feedback_color        0xff9dd274     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  20              \
    bottom_padding               3              \
    left_padding                 3             \
    right_padding                3             \
    window_gap                   3             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# Exclude some app that not match with yabai ratio
yabai -m rule --add app="^(Actualización de software|Diccionario|VLC|Preferencias del Sistema|Ajustes del Sistema|zoom.us|Fotos|FaceTime|Vista Previa|Mensajes|Notas|Utilidad de Discos|App Store|Monitor de Actividad|Música|Calendario|Contactos|Recordatorios)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Acerca de este Mac" app="System Information" title="Acerca de este Mac" manage=off

# Borders focus
borders active_color=0xffffffff inactive_color=0x00000000 width=2 &

# Script to create te 9 desktops
spaces=$(yabai -m query --spaces | jq length)

if [ "$spaces" -ge 10 ]; then
    exit 0
fi

osascript <<EOF
tell application "System Events"
    key code 126 using control down
    delay 0.3
    do shell script "cliclick m:1655,0"
    repeat $((10 - spaces)) times
        do shell script "cliclick c:1655,60"
    end repeat
end tell
EOF




reset
echo "Yabai service reset!"